roaring commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,24 +44,24 @@ jobs:
     - name: Terraform Plan
       run: terraform plan -no-color
 
-    # - name: Terraform Apply
-    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-    #   run: terraform apply -auto-approve
+    - name: Terraform Apply
+      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+      run: terraform apply -auto-approve
 
-    # - name: Get Terraform Outputs
-    #   id: terraform-output
-    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-    #   run: |
-    #     if output=$(terraform output -raw ecr_repository_url 2>&1); then
-    #       echo "ecr_url=${output}" >> $GITHUB_OUTPUT
-    #     else
-    #       echo "Error getting ECR URL: ${output}"
-    #       exit 1
-    #     fi
+    - name: Get Terraform Outputs
+      id: terraform-output
+      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+      run: |
+        if output=$(terraform output -raw ecr_repository_url 2>&1); then
+          echo "ecr_url=${output}" >> $GITHUB_OUTPUT
+        else
+          echo "Error getting ECR URL: ${output}"
+          exit 1
+        fi
 
-    -  name: Terraform Destroy
-       if: github.ref == 'refs/heads/master' && github
-       run: terraform destroy -auto-approve
+    # -  name: Terraform Destroy
+    #    if: github.ref == 'refs/heads/master' && github
+    #    run: terraform destroy -auto-approve
 
   build-and-push:
     runs-on: ubuntu-latest
@@ -83,10 +83,10 @@ jobs:
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
 
-    # - name: Build and push Docker image
-    #   env:
-    #     ECR_REGISTRY: ${{ needs.deploy-infrastructure.outputs.ecr_repository_url }}
-    #     IMAGE_TAG: latest
-    #   run: |
-    #     docker build -t $ECR_REGISTRY:$IMAGE_TAG .
-    #     docker push $ECR_REGISTRY:$IMAGE_TAG
+    - name: Build and push Docker image
+      env:
+        ECR_REGISTRY: ${{ needs.deploy-infrastructure.outputs.ecr_repository_url }}
+        IMAGE_TAG: latest
+      run: |
+        docker build -t $ECR_REGISTRY:$IMAGE_TAG .
+        docker push $ECR_REGISTRY:$IMAGE_TAG
