roaring commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,16 +48,16 @@ jobs:
     #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
     #   run: terraform apply -auto-approve
 
-    - name: Get Terraform Outputs
-      id: terraform-output
-      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-      run: |
-        if output=$(terraform output -raw ecr_repository_url 2>&1); then
-          echo "ecr_url=${output}" >> $GITHUB_OUTPUT
-        else
-          echo "Error getting ECR URL: ${output}"
-          exit 1
-        fi
+    # - name: Get Terraform Outputs
+    #   id: terraform-output
+    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+    #   run: |
+    #     if output=$(terraform output -raw ecr_repository_url 2>&1); then
+    #       echo "ecr_url=${output}" >> $GITHUB_OUTPUT
+    #     else
+    #       echo "Error getting ECR URL: ${output}"
+    #       exit 1
+    #     fi
 
     -  name: Terraform Destroy
        if: github.ref == 'refs/heads/master' && github
